import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { 
  Sparkles, 
  Copy, 
  Check, 
  ShieldCheck, 
  Eye, 
  ArrowLeft,
  Activity,
  CheckCircle2,
  Clock,
  AlertTriangle
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import toast from "react-hot-toast";

export default function ReportSharePage() {
  const { reportId } = useParams();
  const [copied, setCopied] = useState(false);

  const copyToClipboard = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url);
    setCopied(true);
    toast.success("Public share link copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen font-quicksand bg-slate-50 dark:bg-[#020614] text-slate-900 dark:text-white p-4 md:p-8 space-y-8 animate-in fade-in duration-300">
      
      {/* Header Container */}
      <div className="max-w-6xl mx-auto space-y-4">
        <Link 
          to="/reports" 
          className="inline-flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-cyan-600 dark:hover:text-cyan-400 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Reports Center
        </Link>

        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 p-6 rounded-2xl border border-slate-200 dark:border-cyan-500/20 bg-white dark:bg-[#030917]/90 shadow-sm dark:shadow-xl">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400">
              <ShieldCheck size={32} />
            </div>
            <div>
              <h1 className="font-quicksand font-bold text-2xl md:text-3xl tracking-tight text-slate-900 dark:text-white">
                Public Validation Report: Release v2.4.0
              </h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 font-mono">
                Generated by Autonomous AI Testing Agent • {reportId || "REP-9401"}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3 self-start md:self-center">
            <Button 
              onClick={copyToClipboard} 
              className="rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white dark:bg-cyan-500 dark:hover:bg-cyan-400 dark:text-slate-950 font-bold border-none shadow-md dark:shadow-[0_0_15px_rgba(34,211,238,0.3)]"
            >
              {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
              {copied ? "Copied Link" : "Copy Share Link"}
            </Button>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* 4 Metrics Banner */}
        <Card className="rounded-2xl border border-slate-200 dark:border-cyan-500/20 bg-white dark:bg-[#030917]/80 backdrop-blur-xl shadow-sm dark:shadow-lg overflow-hidden">
          <CardContent className="p-0">
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 divide-y sm:divide-y-0 sm:divide-x divide-slate-200 dark:divide-cyan-500/15">
              
              {/* Total Executed */}
              <div className="p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-400">Total Executed</span>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border border-cyan-500/30">
                    <Activity className="h-4 w-4" />
                  </div>
                </div>
                <div className="text-3xl font-bold text-slate-900 dark:text-white">46 Tests</div>
                <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest">
                  Cross-browser test suite
                </div>
              </div>

              {/* Pass Rate */}
              <div className="p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-400">Pass Rate</span>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border border-cyan-500/30">
                    <CheckCircle2 className="h-4 w-4" />
                  </div>
                </div>
                <div className="text-3xl font-bold text-emerald-600 dark:text-emerald-400">91.3%</div>
                <Progress value={91.3} className="h-1.5 bg-slate-100 dark:bg-slate-800 [&_[data-slot=progress-indicator]]:bg-emerald-500" />
              </div>

              {/* Execution Time */}
              <div className="p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-400">Execution Time</span>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border border-cyan-500/30">
                    <Clock className="h-4 w-4" />
                  </div>
                </div>
                <div className="text-3xl font-bold text-slate-900 dark:text-white">4m 12s</div>
                <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest">
                  Parallel worker speed
                </div>
              </div>

              {/* Failed Tests */}
              <div className="p-6 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-400">Failed Tests</span>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/30">
                    <AlertTriangle className="h-4 w-4" />
                  </div>
                </div>
                <div className="text-3xl font-bold text-rose-600 dark:text-rose-400">3 Assertions</div>
                <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest">
                  LLM Root cause identified
                </div>
              </div>
              
            </div>
          </CardContent>
        </Card>

        {/* AI Diagnostic Summary */}
        <Card className="rounded-2xl border border-slate-200 dark:border-cyan-500/20 bg-white dark:bg-[#030917]/90 p-6 space-y-4 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">AI Diagnostic Summary</h3>
              <p className="text-xs text-cyan-600 dark:text-cyan-400/80">Public stakeholder view</p>
            </div>
          </div>

          <div className="p-5 rounded-xl bg-cyan-50/60 dark:bg-[#061026] text-slate-800 dark:text-slate-200 border border-cyan-200/80 dark:border-cyan-500/20 space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-cyan-800 dark:text-cyan-400 font-mono">ROOT CAUSE FINDING</h4>
            <p className="text-sm text-slate-800 dark:text-slate-200 leading-relaxed">
              The runner detected 3 validation failures during special character form input testing on route <code className="text-cyan-800 dark:text-cyan-300 font-mono bg-cyan-100 dark:bg-cyan-500/10 px-1 py-0.5 rounded">/register</code>. Client-side input sanitization threw an uncaught TypeError on null payload parameters.
            </p>
          </div>
        </Card>

        {/* Public Failure Previewer */}
        <Card className="rounded-2xl border border-slate-200 dark:border-cyan-500/20 bg-white dark:bg-[#030917]/90 p-6 space-y-4 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400">
              <Eye className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">Public Failure Previewer</h3>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Failure Exception Log */}
            <div className="space-y-2">
              <span className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Failure Exception Log</span>
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#01040d] border border-slate-200 dark:border-cyan-500/20 font-mono text-xs text-rose-700 dark:text-rose-400 leading-relaxed min-h-[120px]">
                <p>[11:30:04.120] Uncaught TypeError: Cannot read property &apos;validate&apos; of undefined</p>
                <p className="mt-2 text-rose-600 dark:text-rose-400/80">[11:30:04.350] POST /api/v1/auth/register -&gt; 400 Bad Request</p>
              </div>
            </div>

            {/* DOM State Snapshot */}
            <div className="space-y-2">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">DOM State Snapshot</span>
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#01040d] border border-slate-200 dark:border-cyan-500/20 font-mono text-xs text-cyan-800 dark:text-cyan-300 leading-relaxed min-h-[120px]">
                <p>&lt;<span className="text-rose-700 dark:text-rose-400">form</span> <span className="text-purple-700 dark:text-purple-400">id</span>=<span className="text-emerald-700 dark:text-emerald-300">&quot;register-form&quot;</span> <span className="text-purple-700 dark:text-purple-400">class</span>=<span className="text-emerald-700 dark:text-emerald-300">&quot;error-state&quot;</span>&gt; ... &lt;/<span className="text-rose-700 dark:text-rose-400">form</span>&gt;</p>
              </div>
            </div>
          </div>
        </Card>

      </div>
    </div>
  );
}
